# Generated by Django 4.2.7 on 2023-12-08 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darbai', models.CharField(max_length=200, verbose_name='darbai')),
            ],
            options={
                'verbose_name': 'Darbai',
                'verbose_name_plural': 'Darbai',
            },
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darbuotojas', models.CharField(max_length=50, verbose_name='Darbuotojas')),
            ],
            options={
                'verbose_name': 'Darbuotojas',
                'verbose_name_plural': 'Darbuotojai',
            },
        ),
        migrations.CreateModel(
            name='DarbuSarasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laikas', models.DateField(verbose_name='Laikas')),
                ('pastaba', models.TextField(blank=True, max_length=500, verbose_name='Pastaba')),
                ('padaryta', models.BooleanField(default=False, verbose_name='Padaryta')),
                ('darbai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manoapp.darbai')),
                ('darbuotojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manoapp.darbuotojas')),
                ('klientai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Darbu Sarasas',
                'verbose_name_plural': 'Darbu Sarasas',
                'ordering': ['laikas', 'darbuotojas'],
            },
        ),
        migrations.CreateModel(
            name='Komentarai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turinys', models.TextField(max_length=2000, verbose_name='Komentaras')),
                ('data_sukurimo', models.DateTimeField(auto_now_add=True)),
                ('darbas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manoapp.darbusarasas')),
                ('komentatorius', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentaras',
                'verbose_name_plural': 'Komentarai',
                'ordering': ['-data_sukurimo'],
            },
        ),
    ]
