# Generated by Django 4.2.7 on 2023-12-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoapp', '0002_alter_darbusarasas_pastaba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naujienos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antraste', models.CharField(max_length=100, verbose_name='Antraštė')),
                ('naujiena', models.CharField(max_length=1000, verbose_name='Naujiena')),
            ],
            options={
                'verbose_name': 'Naujienos',
                'verbose_name_plural': 'Naujienos',
            },
        ),
    ]
